#!/bin/bash
#SBATCH --job-name=r2p_ablation_A
#SBATCH --account=<YOUR_SLURM_ACCOUNT>
#SBATCH --partition=<YOUR_SLURM_PARTITION>
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=128G
#SBATCH --gres=gpu:1
#SBATCH --time=02:00:00
#SBATCH --output=logs/ablation_A/%j.out
#SBATCH --error=logs/ablation_A/%j.err

echo "=========================================================="
echo "Job started at $(date)"
echo "Running on node: $(hostname)"
nvidia-smi | head -20
echo "=========================================================="

module purge
module load cuda/12.2
module load cudnn

cd <YOUR_PROJECT_DIR>

CONDA_PYTHON=<YOUR_CONDA_ENV_PYTHON>

mkdir -p logs/ablation_E

export R2P_PERVA_DATA=<YOUR_PERVA_DATA_DIR>
export R2P_MODELS_BASE=<YOUR_HF_CACHE_DIR>
export R2P_CLUSTER_MODE=true
export HF_HOME=<YOUR_HF_CACHE_DIR>
export R2P_FLUX_MODEL=<YOUR_FLUX_MODEL_DIR>
export HF_DATASETS_OFFLINE=1
export TRANSFORMERS_OFFLINE=1
export HF_HUB_OFFLINE=1
export PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True"

OUTPUT_DIR=<YOUR_OUTPUT_DIR>/ablation_full_E_full_centroid
DATABASE=database/database_centroid.json
FLUX_PORT=8766

mkdir -p "$OUTPUT_DIR"

FLUX_PID=""
cleanup() {
    if [ -n "$FLUX_PID" ]; then
        echo "🛑 Closing FLUX server (PID=$FLUX_PID)..."
        kill "$FLUX_PID" 2>/dev/null
        wait "$FLUX_PID" 2>/dev/null
        echo "   FLUX server terminated."
    fi
}
trap cleanup EXIT

echo "----------------------------------------------------------"
echo "STAGE 1 — GENERATE ONLY"
echo "----------------------------------------------------------"
CUDA_VISIBLE_DEVICES=0 $CONDA_PYTHON -u flux_loop.py \
    --stage generate_only \
    --database "$DATABASE" \
    --output   "$OUTPUT_DIR"

echo "----------------------------------------------------------"
echo "STAGE 2 — VERIFY BASE"
echo "----------------------------------------------------------"
CUDA_VISIBLE_DEVICES=0 $CONDA_PYTHON -u flux_loop.py \
    --stage verify_base \
    --database "$DATABASE" \
    --output   "$OUTPUT_DIR"

REJECTED_PATH="$OUTPUT_DIR/rejected_concepts.json"

if [ ! -f "$REJECTED_PATH" ]; then
    echo "❌ CRASH: rejected_concepts.json not generated by the verify stage. Interruption."
    exit 1
fi

REJECTED_COUNT=$(python3 -c "import json; print(len(json.load(open('$REJECTED_PATH'))))")

if [ "$REJECTED_COUNT" -eq 0 ]; then
    echo "   ✅ All concepts have passed the verify stage. Refine skipped."
else
    echo "----------------------------------------------------------"
    echo "STAGE 3 — REFINE (Qwen3 on GPU 0 | FLUX on GPU 1)"
    echo "----------------------------------------------------------"
    echo "🚀 Starting FLUX server in background on GPU 1 (port $FLUX_PORT)..."
    
    CUDA_VISIBLE_DEVICES=1 $CONDA_PYTHON flux_server.py --port $FLUX_PORT \
        > "logs/ablation_E/flux_server_${SLURM_JOB_ID}.log" 2>&1 &
    FLUX_PID=$!

    echo "⏳ Waiting for the FLUX server to be ready..."
    FLUX_READY=0
    for i in $(seq 1 60); do
        if curl -s "http://127.0.0.1:$FLUX_PORT/health" > /dev/null 2>&1; then
            echo "   ✅ FLUX Server ready!"
            FLUX_READY=1
            break
        fi
        sleep 10
    done

    if [ "$FLUX_READY" -eq 0 ]; then
        echo "❌ FLUX Server not answering — interruption of the pipeline."
        exit 1
    fi

    CUDA_VISIBLE_DEVICES=0 $CONDA_PYTHON -u flux_loop.py \
        --stage refine \
        --database "$DATABASE" \
        --output   "$OUTPUT_DIR"

    kill "$FLUX_PID" 2>/dev/null
    wait "$FLUX_PID" 2>/dev/null
    FLUX_PID=""
    echo "   🛑 FLUX server stopped."
fi

echo "----------------------------------------------------------"
echo "STAGE 4 — FINAL JUDGE"
echo "----------------------------------------------------------"
CUDA_VISIBLE_DEVICES=0 $CONDA_PYTHON -u flux_loop.py \
    --stage final_judge \
    --database "$DATABASE" \
    --output   "$OUTPUT_DIR"

echo "=========================================================="
echo "Job finished at $(date)"
echo "=========================================================="